# Generated by Django 4.2 on 2023-05-04 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('Fresher', 'Fresher'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Test Lead', 'Test Lead'), ('Manager', 'Manager')], max_length=50)),
                ('location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Noida', 'Noida'), ('Chennai', 'Chennai'), ('Hyderbad', 'Hyderbad')], max_length=50)),
                ('what_relation', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='profileimage')),
                ('resume_upload', models.FileField(blank=True, upload_to='resumedocs')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hr',
        ),
    ]
